### ISSUE TITLE
🪄 Enhancement - Drop Support for Python 3.6 and Django 2.1

### ISSUE THREAD

**Issue by aqeelat** [pysnippet/django-forbid#36]
### Summary

Since Python 3.6 reached EOL a while ago, it might be time to drop support for it. Same thing with Django 2.1 (should be replaced with 2.2).

I can take on this task.

**Comment by ArtyomVancyan** [comment]
Hi @aqeelat, I think there are still applications using Python 3.6 and Django 2.1 versions and lower (I know people who still use Python 2.7). Dropping those versions will shorten the range of supported versions without extending the possibilities of the package.

Anyway, thanks for the passion for contributing to this project. If you have any other suggestions, feature ideas, improvements, etc., please do not hesitate to open a discussion or an issue to discuss your point.

Thanks again!
